create database jagan;
use jagan;
create table students(id int primary key,name varchar(30),age int,gender char(1),mark float);
insert into students  values(1,'jagan',24,'M',98.99);
insert into students values(2,'diyaa',20,'F',99.0),(7,'aneesh',23,'M',97.0),(3,'athira',20,'F',90.0),(4,'hani',27,'M',96.0),(5,'anjana',26,'F',99.0),(6,'sravan',22,'M',89.0);
select*from students;
select name,age from students;
select*from  students where id=2 and 3 ;	
select*from students;
select name,age from students;
select*from students where mark>90;
select*from students where gender='F';
alter table  students add column place varchar(10);
update students set place='wayanad'where id=1;
update students set place='kozhikode'where id=2;
update students set place='idukki' where id=3;
update students set place='kollam'where id=4;
update students set place='kannur'where id=5;
update students set place='ernakulam'where id=6;
update students set place='thrissur'where id=7;
alter table students rename column name to Name;
alter table students rename column id to Id;
alter table students rename column age to Age;
alter table students rename column mark to Mark; 
alter table students rename column place to Place;
select*from students order by Mark desc;
select*from students where Name like 'a%';
